name: AI Code Lint

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  ai-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker container
      run: |
        docker build -t ai-lint:latest .

    - name: Run container and fix files in-place
      run: |
        # Run ai_lint.py which will overwrite the buggy files with fixed code
        docker run --rm -v $GITHUB_WORKSPACE:/app ai-lint:latest python ai_lint.py

    - name: Show changes
      run: |
        echo "=== Git diff after AI Lint ==="
        git --no-pager diff

    - name: Commit and push fixes (optional)
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if ! git diff --cached --quiet; then
          git commit -m "AI Lint: automatically fixed code"
          git push
        else
          echo "✅ No changes detected after AI lint."
        fi
