name: AI Code Lint

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  ai-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full history for diff

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv .venv
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install -r requirements.txt
          .venv/bin/pip install requests fastapi uvicorn

      - name: Get changed Python files
        id: files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' || true)" >> $GITHUB_ENV

      - name: Run AI Lint
        if: env.CHANGED_FILES != ''
        run: |
          echo "[DEBUG] Files to lint: $CHANGED_FILES"
          for f in $CHANGED_FILES; do
            .venv/bin/python ai_lint.py "$f"
          done

      - name: Check for unstaged changes (optional)
        run: |
          if [[ -n $(git diff) ]]; then
            echo "❌ Files were fixed automatically. Please commit the changes."
            git diff
            exit 1
          else
            echo "✅ All files already clean."
          fi
