name: AI Code Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ai-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker container
      run: docker build -t ai-lint:latest .

    - name: Run container and execute lint
      run: |
        docker run --rm -v ${{ github.workspace }}:/app ai-lint:latest python ai_lint.py > lint_results.txt

    - name: Check Lint Results
      run: |
        echo "=== AI Lint Results ==="
        cat lint_results.txt

        if grep -q "BUG" lint_results.txt; then
          echo "❌ Bugs found. Blocking pipeline."
          exit 1
        elif grep -q "SUGGESTION" lint_results.txt; then
          echo "⚠️ Suggestions found. Please review."
        else
          echo "✅ No issues. Proceeding..."
        fi
