name: AI Code Lint

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  ai-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install core Python dependencies
        run: |
          python -m venv .venv
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install -r requirements.txt
          .venv/bin/pip install requests fastapi uvicorn

      - name: Get changed files and install relevant linters
        id: files
        run: |
          # The logic for getting changed files is now more robust
          # for both push and pull_request events.
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | tr '\n' ' ')
          else
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | tr '\n' ' ')
          fi
          
          # A temporary variable to hold the list of changed files with a `.py` extension.
          PYTHON_FILES=$(echo "$CHANGED_FILES" | grep -oE '[^[:space:]]+\.py')
          
          # Install linters only if relevant files are found.
          if [[ -n "$PYTHON_FILES" ]]; then
            echo "Installing Python linters..."
            .venv/bin/pip install flake8 mypy pytest
          fi
          
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

        shell: /usr/bin/bash -e {0}

      - name: Start AI Linting Server
        run: |
          .venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Run AI Lint
        if: env.CHANGED_FILES != ''
        run: |
          echo "[DEBUG] Files to lint: $CHANGED_FILES"
          for f in $CHANGED_FILES; do
            # The script will now be able to find `flake8`, `mypy`, etc.,
            # because they're installed in the virtual environment.
            .venv/bin/python ai_lint.py "$f"
          done

      - name: Check for unstaged changes
        run: |
          git_status=$(git status --porcelain)
          if [[ -n "$git_status" ]]; then
            echo "❌ Files were fixed automatically. Please commit the changes."
            git diff
            exit 1
          else
            echo "✅ All files already clean."
          fi